menu:
  Home: /
  Archives: archives

widgets:
- search
- category
- tag

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: false
  twitter: false
  google: false
  pinterest: true

fancybox: true

google_analytics:
rss:

comment_provider: facebook
# Facebook comment
facebook:
  appid:
  comment_count:
  comment_width:
  comment_colorscheme:
