# 一个workflow，名为deploy to tengxunyun
name: deploy notes
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# 一个 CI/CD 的工作流有许多 jobs 组成，比如最典型的 job 是 lint，test，build。
jobs:
  build: # 构建job
    environment: tx
    runs-on: ubuntu-latest # 跑workflow的服务器系统
    steps: # job的一系列动作
      # 切换分支获取源码
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build

      # 部署到腾讯云服务器
      # 利用action把build好的文件上传到服务器/var/www/react-app路径下,需要确认此目录已在服务端创建
      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.SSH_USER }}   #ssh user name
          server: ${{ secrets.SERVER_IP }} #引用之前创建好的secret
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} #引用之前创建好的secret
          local_path: './public/*'  # 对应我们项目build的文件夹路径
          remote_path: '/home/git/note/'

